version: '2'
services:
    subastados-app:
        image: subastados
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://subastados-mysql:3306/subastados?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    subastados-mysql:
        extends:
            file: mysql.yml
            service: subastados-mysql
