package ar.com.pmp.subastados.domain;

public enum GeneralConfigurationKey {

	PORCENTAJE_OFERTA_PROPUESTA, 
	PORCENTAJE_MINIMO_MENOR_10000, 
	MONTO_MINIMO_10000_20000, 
	MONTO_MINIMO_MAYOR_20000, 
	VIEW_USER_IN_OFFER, 
	USER_VALIDATED_BY_ADMIN, 
	MINUTES_TO_ADD_ON_FINISH,
	URL_LOTE,
	URL_CABALLO,
	URL_FOTO_CABALLO,
	VIEW_AMOUNT_IN_OFFER;
}
